server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ads_management
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
api:
  prefix: api