server:
  port: 8081
  tomcat:
    relaxed-query-chars: "[,]"
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ads_management
    username: root
    password:
api:
  prefix: api
jwt:
  expiration: 120000000
  secretKey: VzzO3+vn3QqsXwTkp982RniBlw+t6PwgIKMX+OMW+78=
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE