server:
  port: 8081
  tomcat:
    relaxed-query-chars: "[,]"
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ads_management
    username: root
    password:
  mail:
    host: smtp.gmail.com
    port: 587
    username: adslord2024@gmail.com
    password: ndtipnjfmxgnrzvl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

api:
  prefix: api
jwt:
  expiration: 120000000
  secretKey: VzzO3+vn3QqsXwTkp982RniBlw+t6PwgIKMX+OMW+78=
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
