server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ads_management_v2
    username: root
    password: huuloc123
api:
  prefix: api
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE