server:
  port: 8081
  tomcat:
    relaxed-query-chars: "[,]"
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ads_management
    username: root
    password:

  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

api:
  prefix: api
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
